---
theme: jordandwhalen
collections:
  projects:
    output: true
    permalink: "/projects/:slug/"
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: single-project
include:
- _pages
permalink: "/:title/"
cloudinary_url: https://res.cloudinary.com/justinlaxamana/
plugins:
- jekyll-inline-svg
header:
  test: Home
  '': "{% svg ../../assets/resources/logo-small.svg %}"
  navigation:
  - template: navlink
    text: Homer
    url: "/"
footer: {}
