---
theme: jordandwhalen
collections:
  projects:
    output: true
    permalink: "/projects/:slug/"
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: single-project
include:
- _pages
permalink: "/:title/"
cloudinary_url: https://res.cloudinary.com/justinlaxamana/
plugins:
- jekyll-inline-svg
header:
  test: Home
  '': "{% svg ../../assets/resources/logo-small.svg %}"
  navigation:
  - template: navlink
    text: Homer
    url: "/"
  link:
  - title: Home
    url: "/"
  - title: Client Work
    url: "/projects"
  dropdown:
  - title: Drift Videos
    sublink:
    - title: Final Bout 3
      url: "/fb3"
    - title: Super D Matsuri 2018
      url: "/masturi"
    - title: Club FR Jam 2018
      url: "/jam"
    - title: Super D Midwest Trial
      url: "/mwt"
    - title: Rio Bash
      url: "/rio"
    - title: Miscellaneous
      url: "/misc"
  button:
  - title: Contact
    url: "/contact"
footer: {}
