---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _projects
  label: Projects
  create: all
  match: "**/*"
upload_dir: ''
public_path: https://res.cloudinary.com/justinlaxamana
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
