---
label: project
hide_body: false
is_partial: false
fields:
- type: text
  name: name
  label: Name
  description: Descriptive name for the project to be used on the backend.
- type: text
  name: client
  label: Client
  description: Name of the client that the work was done for.
  config:
    required: false
  default: Client Name
- type: image_gallery
  name: project_image
  label: Project Image
  description: An image that will be used in hero, and card variations of the project.
- type: textarea
  name: project_description
  label: Project Description
  description: Short description of the work that was done.
  config:
    wysiwyg: true
    schema:
      format: markdown
- type: textarea
  name: project_details
  label: Project Details
  description: Full details of the project.
  config:
    wysiwyg: true
    schema:
      format: markdown
pages:
- _projects/case-study-1.md
